# Generated by Django 3.0.4 on 2020-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200511_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='id',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book or press shift key and select more to select more than one Genre', to='catalog.Genre'),
        ),
    ]
