# Generated by Django 3.0.4 on 2020-05-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200515_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='slug',
            new_name='id',
        ),
    ]
