# Generated by Django 3.0.4 on 2020-05-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200515_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_renew', 'Renew date for books on loan'), ('can_borrow', 'Users can make a borrow request'))},
        ),
    ]
